version: '2'
services:

  redis:
    image: redis
    container_name: gh_analyser_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/redis

  mongo:
    image: mongo
    container_name: github_analyser_mongo
    command: mongod --port 27018
    ports:
      - '27018:27018'
    volumes:
      - ./data/mongo:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    container_name: github_analyser_elastic
    environment:
      - discovery.type=single-node
    volumes:
      - .data/elastic:/data/elastic
    ports:
      - 9200:9200